name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Ensure Docker Compose is available
      run: docker-compose version

    - name: Copy .env.example to .env
      run: cp 25/1-integration-test/.env.example 25/1-integration-test/.env

    - name: Make integration script executable
      run: chmod +x 25/1-integration-test/scripts/run-integration.sh

    - name: Run integration script
      run: cd 25/1-integration-test && ./scripts/run-integration.sh
